channels:
- conda-forge
dependencies:
- python=3.13.1
- pip<=25.0.1
- pip:
  - mlflow==2.20.4
  - cloudpickle==3.1.1
  - dataclasses==0.6
  - numpy==2.1.3
  - pandas==2.2.3
  - pathlib==1.0.1
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
